default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: #username
  password: #password

development:
  <<: *default
  database: mapprr-test_development

test:
  <<: *default
  database: mapprr-test_test

production:
  <<: *default
  database: mapprr-test_production
  username: mapprr-test
  password: <%= ENV['MAPPRR-TEST_DATABASE_PASSWORD'] %>
